import { Image } from "react-grid-gallery";

export const images = [
  {
    src: require("../assets/images/MSK_7423.JPG"),
    original: require("../assets/images/MSK_7423.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7424.JPG"),
    original: require("../assets/images/MSK_7424.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7425.JPG"),
    original: require("../assets/images/MSK_7425.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7426.JPG"),
    original: require("../assets/images/MSK_7426.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7427.JPG"),
    original: require("../assets/images/MSK_7427.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7428.JPG"),
    original: require("../assets/images/MSK_7428.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7430.JPG"),
    original: require("../assets/images/MSK_7430.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7431.JPG"),
    original: require("../assets/images/MSK_7431.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7432.JPG"),
    original: require("../assets/images/MSK_7432.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7433.JPG"),
    original: require("../assets/images/MSK_7433.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7434.JPG"),
    original: require("../assets/images/MSK_7434.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7435.JPG"),
    original: require("../assets/images/MSK_7435.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7436.JPG"),
    original: require("../assets/images/MSK_7436.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7437.JPG"),
    original: require("../assets/images/MSK_7437.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7438.JPG"),
    original: require("../assets/images/MSK_7438.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7439.JPG"),
    original: require("../assets/images/MSK_7439.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7440.JPG"),
    original: require("../assets/images/MSK_7440.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7441.JPG"),
    original: require("../assets/images/MSK_7441.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7441.JPG"),
    original: require("../assets/images/MSK_7442.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7443.JPG"),
    original: require("../assets/images/MSK_7443.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7444.JPG"),
    original: require("../assets/images/MSK_7444.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7445.JPG"),
    original: require("../assets/images/MSK_7445.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7446.JPG"),
    original: require("../assets/images/MSK_7446.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7447.JPG"),
    original: require("../assets/images/MSK_7447.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7448.JPG"),
    original: require("../assets/images/MSK_7448.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7449.JPG"),
    original: require("../assets/images/MSK_7449.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7450.JPG"),
    original: require("../assets/images/MSK_7450.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7451.JPG"),
    original: require("../assets/images/MSK_7451.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7452.JPG"),
    original: require("../assets/images/MSK_7452.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7453.JPG"),
    original: require("../assets/images/MSK_7453.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7455.JPG"),
    original: require("../assets/images/MSK_7455.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7456.JPG"),
    original: require("../assets/images/MSK_7456.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7458.JPG"),
    original: require("../assets/images/MSK_7458.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7459.JPG"),
    original: require("../assets/images/MSK_7459.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7460.JPG"),
    original: require("../assets/images/MSK_7460.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7461.JPG"),
    original: require("../assets/images/MSK_7461.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7462.JPG"),
    original: require("../assets/images/MSK_7462.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7463.JPG"),
    original: require("../assets/images/MSK_7463.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7464.JPG"),
    original: require("../assets/images/MSK_7464.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7465.JPG"),
    original: require("../assets/images/MSK_7465.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7466.JPG"),
    original: require("../assets/images/MSK_7466.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7467.JPG"),
    original: require("../assets/images/MSK_7467.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7468.JPG"),
    original: require("../assets/images/MSK_7468.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7470.JPG"),
    original: require("../assets/images/MSK_7470.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7472.JPG"),
    original: require("../assets/images/MSK_7472.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7473.JPG"),
    original: require("../assets/images/MSK_7473.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7474.JPG"),
    original: require("../assets/images/MSK_7474.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7475.JPG"),
    original: require("../assets/images/MSK_7475.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7476.JPG"),
    original: require("../assets/images/MSK_7476.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7477.JPG"),
    original: require("../assets/images/MSK_7477.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7478.JPG"),
    original: require("../assets/images/MSK_7478.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7479.JPG"),
    original: require("../assets/images/MSK_7479.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7480.JPG"),
    original: require("../assets/images/MSK_7480.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7481.JPG"),
    original: require("../assets/images/MSK_7481.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
  {
    src: require("../assets/images/MSK_7482.JPG"),
    original: require("../assets/images/MSK_7482.JPG"),
    width: 1980,
    height: 1080,
    // tags: [
    //   { value: "", title: "" },
    //   { value: "", title: "" },
    // ],
    // caption: "",
  },
];
